### ISSUE TITLE
npm run dev fail

### ISSUE THREAD

**Issue by yongxinzhang18810492456** [algorithm-visualizer/algorithm-visualizer#246]
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/git/algorithm-visualizer/src/backend/public/algorithms'
    at Object.fs.readdirSync (fs.js:893:3)
    at listFiles (webpack:///./src/backend/common/util.js?:64:28)
    at listDirectories (webpack:///./src/backend/common/util.js?:70:10)
    at Hierarchy.refresh (webpack:///./src/backend/models/Hierarchy.js?:42:51)
    at new Hierarchy (webpack:///./src/backend/models/Hierarchy.js?:34:10)
    at Object.eval (webpack:///./src/backend/common/hierarchy.js?:16:17)
    at eval (webpack:///./src/backend/common/hierarchy.js?:19:30)
    at Object../src/backend/common/hierarchy.js (/home/git/algorithm-visualizer/build/backend/index.js:154:1)
    at __webpack_require__ (/home/git/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/controllers/algorithms.js?:21:18)
    at Object../src/backend/controllers/algorithms.js (/home/git/algorithm-visualizer/build/backend/index.js:190:1)
    at __webpack_require__ (/home/git/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/controllers/index.js?:16:19)
    at Object../src/backend/controllers/index.js (/home/git/algorithm-visualizer/build/backend/index.js:214:1)
    at __webpack_require__ (/home/git/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/index.js?:25:20)

**Comment by parkjs814** [comment]
Please provide a context. Thanks.

**Comment by CN-Yi** [comment]
> @algorithm-visualizer/algorithm-visualizer@2.0.0 start C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer
> cross-env NODE_ENV=production ./bin/www

fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\src\backend\public\algorithms'
    at Object.fs.readdirSync (fs.js:904:18)
    at listFiles (webpack:///./src/backend/common/util.js?:64:28)
    at listDirectories (webpack:///./src/backend/common/util.js?:70:10)
    at Hierarchy.refresh (webpack:///./src/backend/models/Hierarchy.js?:42:51)
    at new Hierarchy (webpack:///./src/backend/models/Hierarchy.js?:34:10)
    at Object.eval (webpack:///./src/backend/common/hierarchy.js?:16:17)
    at eval (webpack:///./src/backend/common/hierarchy.js?:19:30)
    at Object../src/backend/common/hierarchy.js (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:154:1)
    at __webpack_require__ (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:30:30)
    at eval (webpack:///./src/backend/controllers/algorithms.js?:21:18)
    at Object../src/backend/controllers/algorithms.js (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:190:1)
    at __webpack_require__ (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:30:30)
    at eval (webpack:///./src/backend/controllers/index.js?:16:19)
    at Object../src/backend/controllers/index.js (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:214:1)
    at __webpack_require__ (C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer\build\backend\index.js:30:30)
    at eval (webpack:///./src/backend/index.js?:25:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @algorithm-visualizer/algorithm-visualizer@2.0.0 start: `cross-env NODE_ENV=production ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-04T01_52_03_450Z-debug.log
PS C:\Users\Administrator\Desktop\新建文件夹\algorithm-visualizer>

**Comment by chenchujuan** [comment]
不要中文文件夹命名试试？

**Comment by ALMerrill** [comment]
First timer here, and I got this same error on my first time forking, cloning, running npm install and then running npm run dev. I'm on MacOS.

fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/merrill/Development/open_source/algorithm-visualizer/src/backend/public/algorithms'
    at Object.readdirSync (fs.js:809:3)
    at listFiles (webpack:///./src/backend/common/util.js?:64:28)
    at listDirectories (webpack:///./src/backend/common/util.js?:70:10)
    at Hierarchy.refresh (webpack:///./src/backend/models/Hierarchy.js?:42:51)
    at new Hierarchy (webpack:///./src/backend/models/Hierarchy.js?:34:10)
    at Object.eval (webpack:///./src/backend/common/hierarchy.js?:16:17)
    at eval (webpack:///./src/backend/common/hierarchy.js?:19:30)
    at Object../src/backend/common/hierarchy.js (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:154:1)
    at __webpack_require__ (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/controllers/algorithms.js?:21:18)
    at Object../src/backend/controllers/algorithms.js (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:190:1)
    at __webpack_require__ (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/controllers/index.js?:16:19)
    at Object../src/backend/controllers/index.js (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:214:1)
    at __webpack_require__ (/Users/merrill/Development/open_source/algorithm-visualizer/build/backend/index.js:30:30)
    at eval (webpack:///./src/backend/index.js?:25:20)

**Comment by TornjV** [comment]
Hey guys,

For the time being try cloning manually the [algorithms repository](https://github.com/algorithm-visualizer/algorithms) to `algorithm-visualizer/src/backend/public/algorithms`

**Comment by parkjs814** [comment]
Hi @yongxinzhang18810492456, @CN-Yi, and @ALMerrill. I updated the documentation just now. Can you follow [these instructions](https://github.com/algorithm-visualizer/algorithm-visualizer/blob/master/CONTRIBUTING.md#running-locally) to see if it works?

**Comment by ALMerrill** [comment]
Looks like that all worked for me. In addition, when I ran `npm start` it actually opened to `localhost:3000` for me in my browser.
