### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by NeroBlackstone** [algorithm-visualizer/algorithm-visualizer#312]
The node-sass version is 4.12 and it's not compatible to latest node and npm.
Please update dependencies and adapt to latest node.
For now, in node 16.9.1 and npm 7.24. It will throw these error: 

```
    ~/W/algorithm-visualizer    master !2 ?1  npm install            ✔ 
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/×/WebProjects/algorithm-visualizer/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /home/×/WebProjects/algorithm-visualizer/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/home/×/WebProjects/algorithm-visualizer/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/×/WebProjects/algorithm-visualizer/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Linux 5.14.2-1-MANJARO
npm ERR! gyp ERR! command "/usr/bin/node" "/home/×/WebProjects/algorithm-visualizer/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/×/WebProjects/algorithm-visualizer/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

```

**Comment by jomefavourite** [comment]
I'm also getting this same error message whenever I try installing the dependencies

**Comment by jomefavourite** [comment]
I finally got it working, I deleted the package-lock.json file and the node-modules folder. Then uninstalled `node-sass` cause that's the root of the problem.

```bash
npm uninstall node-sass
``` 

Then I installed sass

```
npm i sass
```

Then I ran `npm i`

Still got some errors, but this time the command line showed a fix, the fix (well a temporary fix), is to create an `.env` file then adding this:

```
SKIP_PREFLIGHT_CHECK=true
```

Now, running the command `npm start` works!

**Comment by NeroBlackstone** [comment]
> I finally got it working, I deleted the package-lock.json file and the node-modules folder. Then uninstalled `node-sass` cause that's the root of the problem.
> 
> ```shell
> npm uninstall node-sass
> ```
> 
> Then I installed sass
> 
> ```
> npm i sass
> ```
> 
> Then I ran `npm i`
> 
> Still got some errors, but this time the command line showed a fix, the fix (well a temporary fix), is to create an `.env` file then adding this:
> 
> ```
> SKIP_PREFLIGHT_CHECK=true
> ```
> 
> Now, running the command `npm start` works!

Thanks for your help sincerely, I'll close this issue.

**Comment by jomefavourite** [comment]
You're welcome
